name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Cambia a tu rama principal si es diferente
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/frontend" # Cambia esto si tu proyecto está en otro directorio
          output_location: "build" # Carpeta generada después de `npm run build`
