name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd ./frontend
          npm install

      - name: Build frontend
        run: |
          cd ./frontend
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SAND_0795CC110 }}
          app_location: "./frontend"
          output_location: "build"
