name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      # Instalar dependencias del frontend
      - name: Install dependencies
        run: |
          cd ./frontend
          npm install

      # Construir el frontend
      - name: Build frontend
        run: |
          cd ./frontend
          npm run build

      # Depurar el contenido de app_location
      - name: Debug app_location
        run: ls -R ./frontend

      # Depurar el contenido de output_location
      - name: Debug output_location
        run: ls -R ./frontend/build

      # Desplegar la aplicación
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SAND_0795CC110 }}
          action: "upload"
          app_location: "./frontend"  # Ruta al código fuente del frontend
          api_location: ""  # Ruta a la API (opcional)
          output_location: "build"  # Directorio donde se genera el build
        env:
          ORYX_DEBUG_LOGGING: true  # Habilitar logs de depuración para Oryx

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"