name: Build and deploy Node.js app to Azure Web App - TrucoBeastWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      - name: npm install, build, and test
        run: |
          cd frontend
          npm install
          npm run build --if-present --no-warnings

      - name: Zip artifact for deployment
        run: |
          cd frontend/build
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Esto es necesario para solicitar el JWT.

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          mkdir deploy
          unzip release.zip -d ./deploy
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DC62A1814EE4AAF9BA44CDBB790E9DA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7892288A02B0460FA0C291ECB4FFC19E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2A446AEB9D69418CBEFDF71606709691 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TrucoBeastWeb'
          slot-name: 'Production'
          package: ./deploy
