name: Build and deploy Node.js app to Azure Web App - TrucoBeastWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Install dependencies and build React app
        run: |
          cd frontend
          npm install
          npm run build --if-present --no-warnings

      - name: Compress build folder
        run: zip -r release.zip frontend/build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release

      - name: List files for debugging (Before Unzip)
        run: ls -R

      - name: Unzip the downloaded artifact
        run: |
          unzip release.zip -d extracted_artifact
          unzip extracted_artifact/release.zip -d extracted_build

      - name: List files for verification (After Unzip)
        run: ls -R extracted_build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          auth-type: oidc

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TrucoBeastWeb'
          slot-name: 'Production'
          package: './extracted_build/frontend/build'
